### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by blackthornecl** [toddy994/twitter#3]
I install gem and then: ruby twitter.rb and nothing happens, any idea?

**Comment by toddy994** [comment]
You will have to add you twitter keys in order for it to have access to your account. Open it in an editor and enter them. You can get them by signing up to https://dev.twitter.com/ > create an app and use those keys. You will then have to run bundle exec twitter <name of hashtag> <number to follow>

**Comment by blackthornecl** [comment]
Ok, i create an app and replace keys and tokens, i exec "bundle exec twitter" and login to my account thought cmd line, and get the the PIN: now i get the timeline from my user, but im not following anyone, any idea?

**Comment by blackthornecl** [comment]
Any idea?

**Comment by blackthornecl** [comment]
Any help?
